### ISSUE TITLE
Lua Error that comes up when click on more tab

### ISSUE THREAD

**Issue by Chzconey** [1010101110/Auctionator-classic#1]
Date: 2020-04-06 03:46:37
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\Auctionator\Auctionator.lua line 3146:
   table index is nil
Debug:
   [C]: ?
   Auctionator\Auctionator.lua:3146: Atr_BuildActiveAuctions()
   Auctionator\Auctionator.lua:4670: Atr_BuildGlobalHistoryList()
   Auctionator\Auctionator.lua:3201: Atr_DisplayHlist()
   Auctionator\Auctionator.lua:1355: AuctionFrameTab_OnClick()
   [string "*:OnClick"]:1:
      [string "*:OnClick"]:1

**Comment by 1010101110** [comment]
it works for me, how do i reproduce it?

https://i.imgur.com/nNKDtlr.jpg

**Comment by ghost** [comment]
not to necro a closed issue, but I also get this error when I have no current auctions and click on the more tab. Was this closed because you couldn't reproduce, or because it was fixed?

Edit, i actually did have auctions on the ah when this happened, so my initial assumption about an empty list/table was incorrect. 
For me i clicked on the more tab directly after running a scan, and the scan was ran immediately (or close to) after logging on. I'll see if i can reproduce it some more.

**Comment by 1010101110** [comment]
couldn't reproduce.

yeah i think it has to do with running a scan or checking for undercuts then going to more tab

**Comment by ghost** [comment]
i've only seen it once so its not a big deal by any stretch. otherwise its been a great addon
