### ISSUE TITLE
some error when open auction

### ISSUE THREAD

**Issue by SunnyJang38** [1010101110/Auctionator-classic#15]
11:48 Interface\AddOns\Auctionator\Auctionator-100.0.8.lua:5076: bad argument #1 to 'strlen' (string expected, got nil)
11:48 [C]: in function `strlen'
Interface\AddOns\Auctionator\Auctionator-100.0.8.lua:5076: in function `Atr_Item_Autocomplete'
[string "*:OnCharComposition"]:1: in function <[string "*:OnCharComposition"]:1>
11:48 (*temporary) = nil
(*temporary) = "string expected, got nil"

**Comment by 1010101110** [comment]
that is a bit confusing arg1 variable seems to come from nowhere, maybe this is a copy paste or existing conversion error.

https://github.com/1010101110/Auctionator-classic/blob/f598c1135eca611f6c472b2e69c1f84f36edba81/Auctionator.lua#L5076

**Comment by 1010101110** [comment]
it seems for languages with multiple keypress per character (like Japanese or Chinese) there was some attempt in code to handle autocomplete.

It appears to me that OnChar is perfect because it only returns when a new character (or string) has been inserted. We only need to perform autocomplete when this happens not when character composition is in progress. (i think). 

so remove oncharcomposition all together and remove composition mode check... I can't really test this easily without changing my keyboard.

**Comment by 1010101110** [comment]
i made changes here: bf0242f00d7b8bbfdfde086ec4796fed4916daa6

**Comment by 1010101110** [comment]
@SunnyJang38 you can confirm this fix works or not before i close issue?

**Comment by SunnyJang38** [comment]
> @SunnyJang38 you can confirm this fix works or not before i close issue?

yes, thanks for your work
